server:
  port: 9009

spring:
  mail:
    host: kendy.up.ac.za
    port: 25
    test-connection: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true